# Site settings
title: SR Consulting
email: contato@srconsulting.io
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: _srconsulting
github_username:
whatsapp: (51) 98204-8420
linkedin: https://www.linkedin.com/company/sr-consulting-ltda

# Build settings
markdown: kramdown
